/**
 * supplierApi.js
 *
 * Thin, isolated wrapper around the Kamal Cell supplier API.
 * This is the ONLY file in the whole backend that should know about
 * the supplier's base URL, header name, and response shape.
 *
 * Every other part of the app (order service, catalog service, routes)
 * should go through this module — never call axios/kamal-cell directly
 * from elsewhere. That way, if the supplier changes their API, you
 * only touch this one file.
 */

const axios = require('axios');

const BASE_URL = process.env.SUPPLIER_BASE_URL || 'https://api.kamal-cell.com';
const API_TOKEN = process.env.SUPPLIER_API_TOKEN;

if (!API_TOKEN) {
  // Fail loudly at startup rather than silently sending empty tokens.
  console.warn('[supplierApi] WARNING: SUPPLIER_API_TOKEN is not set. All supplier calls will fail.');
}

const client = axios.create({
  baseURL: BASE_URL,
  timeout: 15000,
  headers: {
    'api-token': API_TOKEN,
  },
});

/**
 * Map of known supplier error codes -> human-readable meaning.
 * Source: supplier API docs (https://api.kamal-cell.com/api-docs)
 */
const ERROR_CODES = {
  120: 'Api Token is required!',
  121: 'Token error',
  122: 'Not allowed to use API',
  123: 'IP not allowed',
  130: 'The site is under maintenance',
  100: 'Insufficient balance',
  105: 'Quantity not available',
  106: 'Quantity not allowed',
  107: 'Player ID blocked',
  108: '2FA required',
  109: 'Product deleted or not found',
  110: 'Product not available now',
  111: 'Try again after 1 minute',
  112: 'Quantity is too small',
  113: 'Quantity is too large',
  114: 'Unknown error',
  500: 'Unknown error',
};

/**
 * Custom error class so callers can distinguish "supplier told us no"
 * from network/unexpected failures, and can branch on the numeric code
 * (e.g. auto-refund wallet on error 100, retry on 111).
 */
class SupplierApiError extends Error {
  constructor(code, message, raw) {
    super(message || ERROR_CODES[code] || `Supplier error ${code}`);
    this.name = 'SupplierApiError';
    this.code = code;
    this.raw = raw;
  }
}

/**
 * Normalizes axios/network errors and supplier-reported error codes
 * into a single SupplierApiError.
 */
function normalizeError(err) {
  if (err.response && err.response.data) {
    const data = err.response.data;
    // Supplier appears to report errors as { status: 'ERROR', code, message } style payloads.
    // Being defensive here since docs don't show the exact error envelope shape.
    const code = data.code || data.error_code || err.response.status;
    const message = data.message || ERROR_CODES[code];
    return new SupplierApiError(code, message, data);
  }
  if (err.code === 'ECONNABORTED') {
    return new SupplierApiError('TIMEOUT', 'Supplier API request timed out', null);
  }
  return new SupplierApiError('NETWORK_ERROR', err.message, null);
}

/**
 * GET /client/api/profile
 * Returns { balance, email }
 */
async function getProfile() {
  try {
    const { data } = await client.get('/client/api/profile');
    return data;
  } catch (err) {
    throw normalizeError(err);
  }
}

/**
 * GET /client/api/products
 * Optionally filter by an array of product IDs, or request minimal data only.
 *
 * @param {Object} opts
 * @param {number[]|string[]} [opts.productIds] - filter to specific product IDs
 * @param {boolean} [opts.minimal] - if true, requests base=1 (id + name only)
 */
async function getProducts(opts = {}) {
  const params = {};
  if (opts.productIds && opts.productIds.length) {
    params.products_id = opts.productIds.join(',');
  }
  if (opts.minimal) {
    params.base = 1;
  }
  try {
    const { data } = await client.get('/client/api/products', { params });
    return data;
  } catch (err) {
    throw normalizeError(err);
  }
}

/**
 * GET /client/api/content/:categoryId
 * categoryId = 0 for the home page (top-level categories/products).
 */
async function getContent(categoryId = 0) {
  try {
    const { data } = await client.get(`/client/api/content/${categoryId}`);
    return data;
  } catch (err) {
    throw normalizeError(err);
  }
}

/**
 * GET /client/api/newOrder/:productId/params
 *
 * Places a new order. `orderUuid` MUST be a fresh UUIDv4 generated by us
 * (see uuid package) and MUST be stored against our local order row
 * BEFORE calling this, so that if our own request dies mid-flight we can
 * safely retry with the same UUID without the supplier double-charging us.
 *
 * @param {Object} args
 * @param {number|string} args.productId
 * @param {number} args.qty
 * @param {string} args.orderUuid - UUIDv4, required, our idempotency key
 * @param {Object} [args.extraParams] - e.g. { playerId: 'xxx' }, product-specific
 */
async function newOrder({ productId, qty, orderUuid, extraParams = {} }) {
  if (!orderUuid) {
    throw new Error('newOrder: orderUuid is required for idempotency');
  }
  const params = {
    qty,
    order_uuid: orderUuid,
    ...extraParams,
  };
  try {
    const { data } = await client.get(`/client/api/newOrder/${productId}/params`, { params });
    return data; // { status: 'OK', data: { order_id, status, price, data, replay_api } }
  } catch (err) {
    throw normalizeError(err);
  }
}

/**
 * GET /client/api/check
 *
 * Check status of one or more orders, by supplier order_id (default)
 * or by our own order_uuid (pass byUuid: true).
 *
 * @param {string[]} orderIdsOrUuids
 * @param {boolean} [byUuid=false]
 */
async function checkOrders(orderIdsOrUuids, byUuid = false) {
  const list = Array.isArray(orderIdsOrUuids) ? orderIdsOrUuids : [orderIdsOrUuids];
  const params = {
    orders: `[${list.join(',')}]`,
  };
  if (byUuid) {
    params.uuid = 1;
  }
  try {
    const { data } = await client.get('/client/api/check', { params });
    return data; // { status: 'OK', data: [ { order_id, status, ... } ] }
  } catch (err) {
    throw normalizeError(err);
  }
}

module.exports = {
  getProfile,
  getProducts,
  getContent,
  newOrder,
  checkOrders,
  SupplierApiError,
  ERROR_CODES,
};
